#define CS 0
#define DS 1
#define ES 2
#define SS 3
#define KS 4
#define IP 5
#define SP 6
#define BP 7
#define CC 8
#define CC 8
#define AC 9
#define EAX 10
#define EBX 11
#define ECX 12
#define EDX 13
#define EEX 14
#define EFX 15
#define CANT_FUNCIONES2 13
#define CANT_FUNCIONES1 11
#define X 3
#define EX 0
#define HIGH 2
#define LOW 1